# ==============================
# Assemble submission-ready supplementary Tables S6 and S7 from machine-readable
# model summaries generated by the component analyses.
# ==============================

required <- c(
  "GSE209746_MSI_sensitivity.csv",
  "tumor_purity_adjust_models.csv",
  "GSE209746_genomic_adjust_models.csv",
  "GSE87211_clinical_utility_models.csv",
  "GSE87211_survival_models.csv",
  "TCGA_READ_survival_models.csv"
)
missing <- required[!file.exists(required)]
if (length(missing)) {
  stop("Missing detailed model summaries: ", paste(missing, collapse = ", "))
}

read_detail <- function(path) {
  read.csv(path, stringsAsFactors = FALSE, check.names = FALSE)
}

msi <- read_detail("GSE209746_MSI_sensitivity.csv")
stroma <- read_detail("tumor_purity_adjust_models.csv")
genomic <- read_detail("GSE209746_genomic_adjust_models.csv")
clinical <- read_detail("GSE87211_clinical_utility_models.csv")
kras <- clinical[clinical$section == "KRAS adjustment", , drop = FALSE]

table_s6 <- rbind(msi, stroma, genomic, kras)
section_order <- c("MSI sensitivity", "Stromal adjustment",
                   "WES genomic adjustment", "KRAS adjustment")
table_s6$section <- factor(table_s6$section, levels = section_order)
table_s6 <- table_s6[order(table_s6$section, table_s6$cohort,
                           table_s6$model, table_s6$focal_term), ]
table_s6$section <- as.character(table_s6$section)

gse_surv <- read_detail("GSE87211_survival_models.csv")
tcga_surv <- read_detail("TCGA_READ_survival_models.csv")
table_s7 <- rbind(gse_surv, tcga_surv)
table_s7 <- table_s7[order(match(table_s7$cohort, c("GSE87211", "TCGA-READ")),
                           match(table_s7$endpoint, c("DFS", "OS", "PFI")),
                           table_s7$model, table_s7$predictor), ]

check_table <- function(x, name) {
  stopifnot(nrow(x) > 0L)
  numeric_required <- c("p_value", "n", "events")
  stopifnot(all(numeric_required %in% names(x)))
  bad_p <- !is.na(x$p_value) & (!is.finite(x$p_value) | x$p_value < 0 | x$p_value > 1)
  if (any(bad_p)) stop(name, ": invalid P values")
  bad_n <- is.na(x$n) | x$n <= 0 | is.na(x$events) | x$events < 0 | x$events > x$n
  if (any(bad_n)) stop(name, ": invalid sample/event counts")
  has_ci <- !is.na(x$ci_lo) | !is.na(x$ci_hi)
  bad_ci <- has_ci & (is.na(x$ci_lo) | is.na(x$ci_hi) |
                        !is.finite(x$ci_lo) | !is.finite(x$ci_hi) |
                        x$ci_lo > x$ci_hi)
  if (any(bad_ci)) stop(name, ": invalid confidence intervals")
  invisible(TRUE)
}

check_table(table_s6, "Table S6")
check_table(table_s7, "Table S7")

write.csv(table_s6, "table_S6_confounder_adjustment.csv", row.names = FALSE, na = "")
write.csv(table_s7, "table_S7_survival_models.csv", row.names = FALSE, na = "")

cat(sprintf("Table S6: %d rows across %d sections\n",
            nrow(table_s6), length(unique(table_s6$section))))
cat(sprintf("Table S7: %d rows across %d cohorts and %d endpoints\n",
            nrow(table_s7), length(unique(table_s7$cohort)),
            length(unique(table_s7$endpoint))))
cat("Outputs: table_S6_confounder_adjustment.csv / table_S7_survival_models.csv\n")
cat("===== Complete =====\n")
